//! Correlation process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::correlation::heston_stoch_corr::HestonStochCorr;
use stochastic_rs_stochastic::correlation::teng::TengSCP;
use stochastic_rs_stochastic::correlation::van_emmerich::VanEmmerich;

process! {
    name: "HestonStochCorr",
    ty: HestonStochCorr<f64>,
    category: Correlation,
    output: MultiDim,
    params: [
        r       : f64     = 0.03 ; "r",
        s0      : f64     = 0.5 ; "Initial spot",
        v0      : f64     = 0.5 ; "Initial variance",
        kappa_v : f64     = 0.5 ; "kappa_v",
        mu_v    : f64     = 0.5 ; "mu_v",
        sigma_v : f64     = 0.5 ; "sigma_v",
        rho0    : f64     = 0.5 ; "rho0",
        kappa_r : f64     = 0.5 ; "kappa_r",
        mu_r    : f64     = 0.5 ; "mu_r",
        sigma_r : f64     = 0.5 ; "sigma_r",
        rho2    : f64     = -0.5 ; "rho2",
        n       : usize   = 1000 ; "Steps",
        t       : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "TengSCP",
    ty: TengSCP<f64>,
    category: Correlation,
    output: Path1D,
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        mu    : f64     = 0.1 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        rho0  : f64     = 0.5 ; "rho0",
        n     : usize   = 1000 ; "Steps",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "VanEmmerich",
    ty: VanEmmerich<f64>,
    category: Correlation,
    output: Path1D,
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        mu    : f64     = 0.1 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        rho0  : f64     = 0.5 ; "rho0",
        n     : usize   = 1000 ; "Steps",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}
