//! Diffusion process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::diffusion::ait_sahalia::AitSahalia;
use stochastic_rs_stochastic::diffusion::cev::Cev;
use stochastic_rs_stochastic::diffusion::cir::Cir;
use stochastic_rs_stochastic::diffusion::ckls::Ckls;
use stochastic_rs_stochastic::diffusion::fcir::Fcir;
use stochastic_rs_stochastic::diffusion::feller::FellerLogistic;
use stochastic_rs_stochastic::diffusion::feller_root::FellerRoot;
use stochastic_rs_stochastic::diffusion::fgbm::Fgbm;
use stochastic_rs_stochastic::diffusion::fjacobi::FJacobi;
use stochastic_rs_stochastic::diffusion::fou::Fou;
use stochastic_rs_stochastic::diffusion::fouque::FouqueOU2D;
use stochastic_rs_stochastic::diffusion::gbm::Gbm;
use stochastic_rs_stochastic::diffusion::gbm_ih::GbmIh;
use stochastic_rs_stochastic::diffusion::gbm_log::GbmLog;
use stochastic_rs_stochastic::diffusion::gompertz::Gompertz;
use stochastic_rs_stochastic::diffusion::hyperbolic2::Hyperbolic2;
use stochastic_rs_stochastic::diffusion::hyperbolic::Hyperbolic;
use stochastic_rs_stochastic::diffusion::jacobi::Jacobi;
use stochastic_rs_stochastic::diffusion::kimura::Kimura;
use stochastic_rs_stochastic::diffusion::linear_sde::LinearSDE;
use stochastic_rs_stochastic::diffusion::logistic::Logistic;
use stochastic_rs_stochastic::diffusion::modified_cir::ModifiedCIR;
use stochastic_rs_stochastic::diffusion::nonlinear_sde::NonLinearSDE;
use stochastic_rs_stochastic::diffusion::ou::Ou;
use stochastic_rs_stochastic::diffusion::pearson::Pearson;
use stochastic_rs_stochastic::diffusion::quadratic::Quadratic;
use stochastic_rs_stochastic::diffusion::radial_ou::RadialOU;
use stochastic_rs_stochastic::diffusion::three_half::ThreeHalf;
use stochastic_rs_stochastic::diffusion::verhulst::Verhulst;

process! {
    name: "AitSahalia",
    ty: AitSahalia<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        am1 : f64     = 0.5 ; "am1",
        a0  : f64     = 0.5 ; "a0",
        a1  : f64     = 0.5 ; "a1",
        a2  : f64     = 0.5 ; "a2",
        b0  : f64     = 0.5 ; "b0",
        b1  : f64     = 0.5 ; "b1",
        b2  : f64     = 0.5 ; "b2",
        b3  : f64     = 0.5 ; "b3",
        n   : usize   = 1000 ; "Steps",
        x0  : opt_f64 = Some(0.5) ; "Initial value",
        t   : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cev",
    ty: Cev<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        mu    : f64     = 0.05 ; "Drift / mean",
        sigma : f64     = 0.3 ; "Diffusion scale",
        gamma : f64     = 0.8 ; "gamma",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(100.0) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cir",
    ty: Cir<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        theta   : f64      = 2.0 ; "Mean / reversion",
        mu      : f64      = 0.5 ; "Drift / mean",
        sigma   : f64      = 0.2 ; "Diffusion scale",
        n       : usize    = 1000 ; "Steps",
        x0      : opt_f64  = Some(0.5) ; "Initial value",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "Ckls",
    ty: Ckls<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        theta1 : f64     = 0.5 ; "theta1",
        theta2 : f64     = 0.5 ; "theta2",
        theta3 : f64     = 0.5 ; "theta3",
        theta4 : f64     = 0.5 ; "theta4",
        n      : usize   = 1000 ; "Steps",
        x0     : opt_f64 = Some(0.5) ; "Initial value",
        t      : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Fcir",
    ty: Fcir<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        hurst   : f64      = 0.4 ; "Hurst exponent",
        theta   : f64      = 0.5 ; "Mean / reversion",
        mu      : f64      = 0.1 ; "Drift / mean",
        sigma   : f64      = 0.2 ; "Diffusion scale",
        n       : usize    = 1000 ; "Steps",
        x0      : opt_f64  = Some(0.5) ; "Initial value",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "FellerLogistic",
    ty: FellerLogistic<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa   : f64      = 1.5 ; "Reversion speed",
        theta   : f64      = 0.5 ; "Mean / reversion",
        sigma   : f64      = 0.2 ; "Diffusion scale",
        n       : usize    = 1000 ; "Steps",
        x0      : opt_f64  = Some(0.5) ; "Initial value",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "FellerRoot",
    ty: FellerRoot<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        theta1 : f64     = 0.5 ; "theta1",
        theta2 : f64     = 0.5 ; "theta2",
        theta3 : f64     = 0.5 ; "theta3",
        n      : usize   = 1000 ; "Steps",
        x0     : opt_f64 = Some(0.5) ; "Initial value",
        t      : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Fgbm",
    ty: Fgbm<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        mu    : f64     = 0.05 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(100.0) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "FJacobi",
    ty: FJacobi<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        alpha : f64     = 0.3 ; "alpha",
        beta  : f64     = 0.7 ; "beta",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Fou",
    ty: Fou<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        theta : f64     = 1.0 ; "Mean / reversion",
        mu    : f64     = 1.0 ; "Drift / mean",
        sigma : f64     = 0.3 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "FouqueOU2D",
    ty: FouqueOU2D<f64>,
    category: Diffusion,
    output: MultiDim,
    components: ["x1", "x2"],
    params: [
        kappa   : f64     = 1.5 ; "Reversion speed",
        theta   : f64     = 0.5 ; "Mean / reversion",
        epsilon : f64     = 0.3 ; "epsilon",
        alpha   : f64     = 0.5 ; "alpha",
        n       : usize   = 1000 ; "Steps",
        x0      : opt_f64 = Some(0.5) ; "Initial value",
        y0      : opt_f64 = Some(0.5) ; "y0",
        t       : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Gbm",
    ty: Gbm<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        mu    : f64     = 0.05 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(100.0) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "GbmIh",
    ty: GbmIh<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        mu     : f64        = 0.1 ; "Drift / mean",
        sigma  : f64        = 0.2 ; "Diffusion scale",
        n      : usize      = 1000 ; "Steps",
        x0     : opt_f64    = Some(0.5) ; "Initial value",
        t      : opt_f64    = Some(1.0) ; "Horizon",
        sigmas : opt_f64vec = None ; "sigmas",
    ],
}

process! {
    name: "GbmLog",
    ty: GbmLog<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        mu    : opt_f64 = Some(0.1) ; "Drift / mean",
        b     : opt_f64 = Some(0.1) ; "b",
        r     : opt_f64 = Some(0.03) ; "r",
        r_f   : opt_f64 = Some(0.02) ; "r_f",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        s0    : opt_f64 = Some(100.0) ; "Initial spot",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Gompertz",
    ty: Gompertz<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        a     : f64     = 0.5 ; "a",
        b     : f64     = 0.5 ; "b",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Hyperbolic",
    ty: Hyperbolic<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Hyperbolic2",
    ty: Hyperbolic2<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        beta  : f64     = 0.5 ; "beta",
        gamma : f64     = 0.5 ; "gamma",
        delta : f64     = 0.5 ; "delta",
        mu    : f64     = 0.1 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Jacobi",
    ty: Jacobi<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        alpha : f64     = 0.3 ; "alpha",
        beta  : f64     = 0.7 ; "beta",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Kimura",
    ty: Kimura<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        a     : f64     = 0.5 ; "a",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "LinearSDE",
    ty: LinearSDE<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        a  : f64     = 0.5 ; "a",
        b  : f64     = 0.5 ; "b",
        c  : f64     = 1.0 ; "c",
        n  : usize   = 1000 ; "Steps",
        x0 : opt_f64 = Some(0.5) ; "Initial value",
        t  : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Logistic",
    ty: Logistic<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        a  : f64     = 0.5 ; "a",
        b  : f64     = 0.5 ; "b",
        n  : usize   = 1000 ; "Steps",
        x0 : opt_f64 = Some(0.5) ; "Initial value",
        t  : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "ModifiedCIR",
    ty: ModifiedCIR<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "NonLinearSDE",
    ty: NonLinearSDE<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        am1 : f64     = 0.5 ; "am1",
        a0  : f64     = 0.5 ; "a0",
        a1  : f64     = 0.5 ; "a1",
        a2  : f64     = 0.5 ; "a2",
        b0  : f64     = 0.5 ; "b0",
        b1  : f64     = 0.5 ; "b1",
        b2  : f64     = 0.5 ; "b2",
        b3  : f64     = 0.5 ; "b3",
        n   : usize   = 1000 ; "Steps",
        x0  : opt_f64 = Some(0.5) ; "Initial value",
        t   : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Ou",
    ty: Ou<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        theta : f64     = 1.0 ; "Mean / reversion",
        mu    : f64     = 1.2 ; "Drift / mean",
        sigma : f64     = 0.3 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Pearson",
    ty: Pearson<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        mu    : f64     = 0.1 ; "Drift / mean",
        a     : f64     = 0.5 ; "a",
        b     : f64     = 0.5 ; "b",
        c     : f64     = 1.0 ; "c",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Quadratic",
    ty: Quadratic<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        alpha : f64     = 0.5 ; "alpha",
        beta  : f64     = 0.5 ; "beta",
        gamma : f64     = 0.5 ; "gamma",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "RadialOU",
    ty: RadialOU<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "ThreeHalf",
    ty: ThreeHalf<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        kappa : f64     = 1.5 ; "Reversion speed",
        mu    : f64     = 0.1 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Verhulst",
    ty: Verhulst<f64>,
    category: Diffusion,
    output: Path1D,
    components: [],
    params: [
        r     : f64      = 0.03 ; "r",
        k     : f64      = 1.0 ; "k",
        sigma : f64      = 0.2 ; "Diffusion scale",
        n     : usize    = 1000 ; "Steps",
        x0    : opt_f64  = Some(0.5) ; "Initial value",
        t     : opt_f64  = Some(1.0) ; "Horizon",
        clamp : opt_bool = Some(true) ; "Clamp positive",
    ],
}
