//! Jump process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::jump::bilateral_gamma::BilateralGamma;
use stochastic_rs_stochastic::jump::cgmy::Cgmy;
use stochastic_rs_stochastic::jump::cts::Cts;
use stochastic_rs_stochastic::jump::hawkes_jd::HawkesJD;
use stochastic_rs_stochastic::jump::ig::Ig;
use stochastic_rs_stochastic::jump::kobol::KoBoL;
use stochastic_rs_stochastic::jump::mjd_log::MjdLog;
use stochastic_rs_stochastic::jump::nig::Nig;
use stochastic_rs_stochastic::jump::rdts::Rdts;
use stochastic_rs_stochastic::jump::vg::Vg;

process! {
    name: "BilateralGamma",
    ty: BilateralGamma<f64>,
    category: Jump,
    output: Path1D,
    params: [
        alpha_p  : f64     = 0.5 ; "alpha_p",
        lambda_p : f64     = 0.5 ; "lambda_p",
        alpha_m  : f64     = 0.5 ; "alpha_m",
        lambda_m : f64     = 0.5 ; "lambda_m",
        n        : usize   = 1000 ; "Steps",
        x0       : opt_f64 = Some(0.5) ; "Initial value",
        t        : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cgmy",
    ty: Cgmy<f64>,
    category: Jump,
    output: Path1D,
    params: [
        c            : f64     = 1.0 ; "c",
        lambda_plus  : f64     = 0.5 ; "lambda_plus",
        lambda_minus : f64     = 0.5 ; "lambda_minus",
        alpha        : f64     = 0.5 ; "alpha",
        n            : usize   = 1000 ; "Steps",
        j            : usize   = 50 ; "j",
        x0           : opt_f64 = Some(0.5) ; "Initial value",
        t            : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cts",
    ty: Cts<f64>,
    category: Jump,
    output: Path1D,
    params: [
        lambda_plus  : f64     = 0.5 ; "lambda_plus",
        lambda_minus : f64     = 0.5 ; "lambda_minus",
        alpha        : f64     = 0.5 ; "alpha",
        n            : usize   = 1000 ; "Steps",
        j            : usize   = 50 ; "j",
        x0           : opt_f64 = Some(0.5) ; "Initial value",
        t            : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "HawkesJD",
    ty: HawkesJD<f64>,
    category: Jump,
    output: Path1D,
    params: [
        mu        : f64     = 0.1 ; "Drift / mean",
        sigma     : f64     = 0.2 ; "Diffusion scale",
        mu_lambda : f64     = 0.5 ; "mu_lambda",
        alpha     : f64     = 0.5 ; "alpha",
        beta      : f64     = 1.5 ; "beta",
        mu_j      : f64     = 0.5 ; "mu_j",
        sigma_j   : f64     = 0.5 ; "sigma_j",
        n         : usize   = 1000 ; "Steps",
        x0        : opt_f64 = Some(0.5) ; "Initial value",
        t         : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Ig",
    ty: Ig<f64>,
    category: Jump,
    output: Path1D,
    params: [
        gamma : f64     = 0.5 ; "gamma",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "KoBoL",
    ty: KoBoL<f64>,
    category: Jump,
    output: Path1D,
    params: [
        d            : f64     = 0.5 ; "d",
        p            : f64     = 0.5 ; "p",
        q            : f64     = 0.5 ; "q",
        lambda_plus  : f64     = 0.5 ; "lambda_plus",
        lambda_minus : f64     = 0.5 ; "lambda_minus",
        alpha        : f64     = 0.5 ; "alpha",
        n            : usize   = 1000 ; "Steps",
        j            : usize   = 50 ; "j",
        x0           : opt_f64 = Some(0.5) ; "Initial value",
        t            : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "MjdLog",
    ty: MjdLog<f64>,
    category: Jump,
    output: Path1D,
    params: [
        mu     : opt_f64 = Some(0.1) ; "Drift / mean",
        b      : opt_f64 = Some(0.1) ; "b",
        r      : opt_f64 = Some(0.03) ; "r",
        r_f    : opt_f64 = Some(0.02) ; "r_f",
        sigma  : f64     = 0.2 ; "Diffusion scale",
        lambda : f64     = 1.0 ; "Jump intensity",
        nu     : f64     = 0.2 ; "nu",
        omega  : f64     = 0.2 ; "omega",
        n      : usize   = 1000 ; "Steps",
        s0     : opt_f64 = Some(100.0) ; "Initial spot",
        t      : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Nig",
    ty: Nig<f64>,
    category: Jump,
    output: Path1D,
    params: [
        theta : f64     = 0.5 ; "Mean / reversion",
        sigma : f64     = 0.2 ; "Diffusion scale",
        kappa : f64     = 1.5 ; "Reversion speed",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Rdts",
    ty: Rdts<f64>,
    category: Jump,
    output: Path1D,
    params: [
        lambda_plus  : f64     = 0.5 ; "lambda_plus",
        lambda_minus : f64     = 0.5 ; "lambda_minus",
        alpha        : f64     = 0.5 ; "alpha",
        n            : usize   = 1000 ; "Steps",
        j            : usize   = 50 ; "j",
        x0           : opt_f64 = Some(0.5) ; "Initial value",
        t            : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Vg",
    ty: Vg<f64>,
    category: Jump,
    output: Path1D,
    params: [
        mu    : f64     = 0.1 ; "Drift / mean",
        sigma : f64     = 0.2 ; "Diffusion scale",
        nu    : f64     = 0.2 ; "nu",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}
