//! Process process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::process::bm::Bm;
use stochastic_rs_stochastic::process::cbms::Cbms;
use stochastic_rs_stochastic::process::cfbms::Cfbms;
use stochastic_rs_stochastic::process::fbm::Fbm;
use stochastic_rs_stochastic::process::hawkes::Hawkes;
use stochastic_rs_stochastic::process::lfsm::Lfsm;
use stochastic_rs_stochastic::process::poisson::Poisson;
use stochastic_rs_stochastic::process::subordinator::alpha_stable::AlphaStableSubordinator;
use stochastic_rs_stochastic::process::subordinator::gamma_subordinator::GammaSubordinator;
use stochastic_rs_stochastic::process::subordinator::ig_subordinator::IGSubordinator;
use stochastic_rs_stochastic::process::subordinator::inverse_alpha_stable::InverseAlphaStableSubordinator;
use stochastic_rs_stochastic::process::subordinator::poisson_subordinator::PoissonSubordinator;
use stochastic_rs_stochastic::process::subordinator::tempered_stable::TemperedStableSubordinator;

process! {
    name: "Bm",
    ty: Bm<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        n : usize   = 1000 ; "Steps",
        t : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cbms",
    ty: Cbms<f64>,
    category: Process,
    output: MultiDim,
    components: ["x1", "x2"],
    params: [
        rho : f64     = -0.5 ; "Correlation",
        n   : usize   = 1000 ; "Steps",
        t   : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Cfbms",
    ty: Cfbms<f64>,
    category: Process,
    output: MultiDim,
    components: ["x1", "x2"],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        rho   : f64     = -0.5 ; "Correlation",
        n     : usize   = 1000 ; "Steps",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Fbm",
    ty: Fbm<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        n     : usize   = 1000 ; "Steps",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Hawkes",
    ty: Hawkes<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        mu    : f64       = 0.1 ; "Drift / mean",
        alpha : f64       = 0.5 ; "alpha",
        beta  : f64       = 1.5 ; "beta",
        n     : opt_usize = Some(1) ; "Steps",
        t_max : opt_f64   = Some(0.5) ; "t_max",
    ],
}

process! {
    name: "Lfsm",
    ty: Lfsm<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        alpha : f64     = 1.5 ; "alpha",
        beta  : f64     = 0.5 ; "beta",
        hurst : f64     = 0.8 ; "Hurst exponent",
        scale : f64     = 0.5 ; "scale",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Poisson",
    ty: Poisson<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        lambda : f64       = 1.0 ; "Jump intensity",
        n      : opt_usize = Some(1) ; "Steps",
        t_max  : opt_f64   = Some(0.5) ; "t_max",
    ],
}

process! {
    name: "AlphaStableSubordinator",
    ty: AlphaStableSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        alpha : f64     = 0.5 ; "alpha",
        c     : f64     = 1.0 ; "c",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "GammaSubordinator",
    ty: GammaSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        nu   : f64     = 0.2 ; "nu",
        rate : f64     = 0.5 ; "rate",
        n    : usize   = 1000 ; "Steps",
        x0   : opt_f64 = Some(0.5) ; "Initial value",
        t    : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "IGSubordinator",
    ty: IGSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        delta : f64     = 0.5 ; "delta",
        gamma : f64     = 0.5 ; "gamma",
        n     : usize   = 1000 ; "Steps",
        x0    : opt_f64 = Some(0.5) ; "Initial value",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "InverseAlphaStableSubordinator",
    ty: InverseAlphaStableSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        alpha   : f64     = 0.5 ; "alpha",
        c       : f64     = 1.0 ; "c",
        n       : usize   = 1000 ; "Steps",
        t       : opt_f64 = Some(1.0) ; "Horizon",
        u_steps : usize   = 64 ; "u_steps",
        u_max   : opt_f64 = Some(0.5) ; "u_max",
    ],
}

process! {
    name: "PoissonSubordinator",
    ty: PoissonSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        lambda : f64     = 1.0 ; "Jump intensity",
        n      : usize   = 1000 ; "Steps",
        x0     : opt_f64 = Some(0.5) ; "Initial value",
        t      : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "TemperedStableSubordinator",
    ty: TemperedStableSubordinator<f64>,
    category: Process,
    output: Path1D,
    components: [],
    params: [
        alpha   : f64     = 0.5 ; "alpha",
        c       : f64     = 1.0 ; "c",
        mu      : f64     = 0.1 ; "Drift / mean",
        epsilon : f64     = 0.3 ; "epsilon",
        n       : usize   = 1000 ; "Steps",
        x0      : opt_f64 = Some(0.5) ; "Initial value",
        t       : opt_f64 = Some(1.0) ; "Horizon",
    ],
}
