//! Rough process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::rough::rl_bs::RlBlackScholes;
use stochastic_rs_stochastic::rough::rl_fbm::RlFBm;
use stochastic_rs_stochastic::rough::rl_fou::RlFOU;
use stochastic_rs_stochastic::rough::rl_heston::RlHeston;

process! {
    name: "RlBlackScholes",
    ty: RlBlackScholes<f64>,
    category: Rough,
    output: Path1D,
    components: [],
    params: [
        hurst  : f64       = 0.4 ; "Hurst exponent",
        s0     : f64       = 0.5 ; "Initial spot",
        r      : f64       = 0.03 ; "r",
        sigma  : f64       = 0.2 ; "Diffusion scale",
        n      : usize     = 1000 ; "Steps",
        t      : opt_f64   = Some(1.0) ; "Horizon",
        degree : opt_usize = Some(1) ; "Approximation degree",
    ],
}

process! {
    name: "RlFBm",
    ty: RlFBm<f64>,
    category: Rough,
    output: Path1D,
    components: [],
    params: [
        hurst  : f64       = 0.4 ; "Hurst exponent",
        n      : usize     = 1000 ; "Steps",
        t      : opt_f64   = Some(1.0) ; "Horizon",
        degree : opt_usize = Some(1) ; "Approximation degree",
    ],
}

process! {
    name: "RlFOU",
    ty: RlFOU<f64>,
    category: Rough,
    output: Path1D,
    components: [],
    params: [
        hurst  : f64       = 0.4 ; "Hurst exponent",
        kappa  : f64       = 1.5 ; "Reversion speed",
        mu     : f64       = 0.1 ; "Drift / mean",
        sigma  : f64       = 0.2 ; "Diffusion scale",
        n      : usize     = 1000 ; "Steps",
        x0     : opt_f64   = Some(0.5) ; "Initial value",
        t      : opt_f64   = Some(1.0) ; "Horizon",
        degree : opt_usize = Some(1) ; "Approximation degree",
    ],
}

process! {
    name: "RlHeston",
    ty: RlHeston<f64>,
    category: Rough,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        hurst  : f64       = 0.4 ; "Hurst exponent",
        s0     : opt_f64   = Some(100.0) ; "Initial spot",
        v0     : opt_f64   = Some(0.04) ; "Initial variance",
        kappa  : f64       = 1.5 ; "Reversion speed",
        theta  : f64       = 0.5 ; "Mean / reversion",
        sigma  : f64       = 0.2 ; "Diffusion scale",
        rho    : f64       = -0.5 ; "Correlation",
        mu     : f64       = 0.1 ; "Drift / mean",
        n      : usize     = 1000 ; "Steps",
        t      : opt_f64   = Some(1.0) ; "Horizon",
        degree : opt_usize = Some(1) ; "Approximation degree",
    ],
}
