//! Sheet process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::sheet::fbs::Fbs;

process! {
    name: "Fbs",
    ty: Fbs<f64>,
    category: Sheet,
    output: Curve,
    components: [],
    params: [
        hurst : f64   = 0.4 ; "Hurst exponent",
        m     : usize = 64 ; "m",
        n     : usize = 1000 ; "Steps",
        r     : f64   = 1.0 ; "r",
    ],
}
