//! Volatility process registrations (generated by tools/gen.py).

use crate::process;
use stochastic_rs_stochastic::volatility::bates_svj::BatesSvj;
use stochastic_rs_stochastic::volatility::bergomi::Bergomi;
use stochastic_rs_stochastic::volatility::bns::Bns;
use stochastic_rs_stochastic::volatility::double_heston::DoubleHeston;
use stochastic_rs_stochastic::volatility::fbates_svj::FBatesSvj;
use stochastic_rs_stochastic::volatility::fheston::RoughHeston;
use stochastic_rs_stochastic::volatility::heston_log::HestonLog;
use stochastic_rs_stochastic::volatility::hkde::Hkde;
use stochastic_rs_stochastic::volatility::rbergomi::RoughBergomi;
use stochastic_rs_stochastic::volatility::sabr::Sabr;
use stochastic_rs_stochastic::volatility::svcgmy::Svcgmy;

process! {
    name: "BatesSvj",
    ty: BatesSvj<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        mu      : opt_f64  = Some(0.1) ; "Drift / mean",
        b       : opt_f64  = Some(0.1) ; "b",
        r       : opt_f64  = Some(0.03) ; "r",
        r_f     : opt_f64  = Some(0.02) ; "r_f",
        lambda  : f64      = 1.0 ; "Jump intensity",
        nu      : f64      = 0.2 ; "nu",
        omega   : f64      = 0.2 ; "omega",
        alpha   : f64      = 0.5 ; "alpha",
        beta    : f64      = 0.5 ; "beta",
        sigma   : f64      = 0.2 ; "Diffusion scale",
        rho     : f64      = -0.5 ; "Correlation",
        n       : usize    = 1000 ; "Steps",
        s0      : opt_f64  = Some(100.0) ; "Initial spot",
        v0      : opt_f64  = Some(0.04) ; "Initial variance",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "Bergomi",
    ty: Bergomi<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        nu  : f64     = 0.2 ; "nu",
        v0  : opt_f64 = Some(0.04) ; "Initial variance",
        s0  : opt_f64 = Some(100.0) ; "Initial spot",
        r   : f64     = 0.03 ; "r",
        rho : f64     = -0.5 ; "Correlation",
        n   : usize   = 1000 ; "Steps",
        t   : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Bns",
    ty: Bns<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        s0         : opt_f64 = Some(100.0) ; "Initial spot",
        sigma2_0   : f64     = 0.5 ; "sigma2_0",
        lambda     : f64     = 1.0 ; "Jump intensity",
        mu         : f64     = 0.1 ; "Drift / mean",
        nu         : f64     = 0.2 ; "nu",
        jump_shape : f64     = 0.5 ; "jump_shape",
        n          : usize   = 1000 ; "Steps",
        t          : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "DoubleHeston",
    ty: DoubleHeston<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance", "variance 2"],
    params: [
        s0      : opt_f64  = Some(100.0) ; "Initial spot",
        v1_0    : opt_f64  = Some(0.5) ; "v1_0",
        v2_0    : opt_f64  = Some(0.5) ; "v2_0",
        kappa1  : f64      = 0.5 ; "kappa1",
        theta1  : f64      = 0.5 ; "theta1",
        sigma1  : f64      = 0.2 ; "sigma1",
        rho1    : f64      = -0.5 ; "rho1",
        kappa2  : f64      = 0.5 ; "kappa2",
        theta2  : f64      = 0.5 ; "theta2",
        sigma2  : f64      = 0.2 ; "sigma2",
        rho2    : f64      = -0.5 ; "rho2",
        mu      : f64      = 0.1 ; "Drift / mean",
        n       : usize    = 1000 ; "Steps",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "FBatesSvj",
    ty: FBatesSvj<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        hurst  : f64     = 0.4 ; "Hurst exponent",
        mu     : f64     = 0.1 ; "Drift / mean",
        s0     : f64     = 0.5 ; "Initial spot",
        v0     : f64     = 0.5 ; "Initial variance",
        theta  : f64     = 0.5 ; "Mean / reversion",
        kappa  : f64     = 1.5 ; "Reversion speed",
        xi     : f64     = 0.04 ; "xi",
        rho    : f64     = -0.5 ; "Correlation",
        lambda : f64     = 1.0 ; "Jump intensity",
        nu     : f64     = 0.2 ; "nu",
        omega  : f64     = 0.2 ; "omega",
        n      : usize   = 1000 ; "Steps",
        t      : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "RoughHeston",
    ty: RoughHeston<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        v0    : opt_f64 = Some(0.04) ; "Initial variance",
        theta : f64     = 0.5 ; "Mean / reversion",
        kappa : f64     = 1.5 ; "Reversion speed",
        nu    : f64     = 0.2 ; "nu",
        c1    : opt_f64 = Some(0.5) ; "c1",
        c2    : opt_f64 = Some(0.5) ; "c2",
        t     : opt_f64 = Some(1.0) ; "Horizon",
        n     : usize   = 1000 ; "Steps",
    ],
}

process! {
    name: "HestonLog",
    ty: HestonLog<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        mu      : opt_f64  = Some(0.1) ; "Drift / mean",
        b       : opt_f64  = Some(0.1) ; "b",
        r       : opt_f64  = Some(0.03) ; "r",
        r_f     : opt_f64  = Some(0.02) ; "r_f",
        kappa   : f64      = 1.5 ; "Reversion speed",
        theta   : f64      = 0.5 ; "Mean / reversion",
        xi      : f64      = 0.04 ; "xi",
        rho     : f64      = -0.5 ; "Correlation",
        n       : usize    = 1000 ; "Steps",
        s0      : opt_f64  = Some(100.0) ; "Initial spot",
        v0      : opt_f64  = Some(0.04) ; "Initial variance",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "Hkde",
    ty: Hkde<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        mu      : f64      = 0.1 ; "Drift / mean",
        kappa   : f64      = 1.5 ; "Reversion speed",
        theta   : f64      = 0.5 ; "Mean / reversion",
        sigma_v : f64      = 0.5 ; "sigma_v",
        rho     : f64      = -0.5 ; "Correlation",
        v0      : f64      = 0.5 ; "Initial variance",
        lambda  : f64      = 1.0 ; "Jump intensity",
        p_up    : f64      = 0.5 ; "p_up",
        eta1    : f64      = 3.0 ; "eta1",
        eta2    : f64      = 3.0 ; "eta2",
        n       : usize    = 1000 ; "Steps",
        s0      : opt_f64  = Some(100.0) ; "Initial spot",
        t       : opt_f64  = Some(1.0) ; "Horizon",
        use_sym : opt_bool = Some(true) ; "Symmetrise",
    ],
}

process! {
    name: "RoughBergomi",
    ty: RoughBergomi<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        hurst : f64     = 0.4 ; "Hurst exponent",
        nu    : f64     = 0.2 ; "nu",
        v0    : opt_f64 = Some(0.04) ; "Initial variance",
        s0    : opt_f64 = Some(100.0) ; "Initial spot",
        r     : f64     = 0.03 ; "r",
        rho   : f64     = -0.5 ; "Correlation",
        n     : usize   = 1000 ; "Steps",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Sabr",
    ty: Sabr<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        alpha : f64     = 0.5 ; "alpha",
        beta  : f64     = 0.5 ; "beta",
        rho   : f64     = -0.5 ; "Correlation",
        n     : usize   = 1000 ; "Steps",
        f0    : opt_f64 = Some(0.5) ; "f0",
        v0    : opt_f64 = Some(0.04) ; "Initial variance",
        t     : opt_f64 = Some(1.0) ; "Horizon",
    ],
}

process! {
    name: "Svcgmy",
    ty: Svcgmy<f64>,
    category: Volatility,
    output: MultiDim,
    components: ["asset", "variance"],
    params: [
        lambda_plus  : f64     = 0.5 ; "lambda_plus",
        lambda_minus : f64     = 0.5 ; "lambda_minus",
        alpha        : f64     = 0.5 ; "alpha",
        kappa        : f64     = 1.5 ; "Reversion speed",
        eta          : f64     = 0.4 ; "eta",
        zeta         : f64     = 0.5 ; "zeta",
        rho          : f64     = -0.5 ; "Correlation",
        n            : usize   = 1000 ; "Steps",
        j            : usize   = 50 ; "j",
        x0           : opt_f64 = Some(0.5) ; "Initial value",
        v0           : opt_f64 = Some(0.04) ; "Initial variance",
        t            : opt_f64 = Some(1.0) ; "Horizon",
    ],
}
